name: Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
      - name: check
        run: echo ${{ secrets.DEV_TOKEN }}

      - name: deploy
        run: ls

  deploy:
    needs: [plan]
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: check
        run: echo ${{ secrets.PROD_TOKEN }}

      - name: deploy
        run: ls


