name: Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
      - name: deploy
        run: ls
